# Directories used in workflow.
ANALYSIS_DIR: "analysis"
DATA_DIR: "data"
EXP_DIR: "experiments"
IGV_DIR: "igv"
SAMPLES_DIR: "samples"
TRASH_DIR: "trash"
SCRIPTS_DIR: "workflow/scripts"

# Path to download data from.
RSYNC_PATH: 'niairplggcgu.irp.nia.nih.gov:/store/seq/ont/experiments/'

# Other variables.
ASSEMBLY: 'hg38'

# Sample data
SAMPLE_DATA: [
    ['hsa_dRNA_Huh7_mock_1', 'SQK-RNA002', 'FLO-PRO002', '20220920_hsa_dRNA_Huh7_mock_1'],
    ['hsa_dRNA_Huh7_EBOV_6h_1', 'SQK-RNA002', 'FLO-PRO002', '20220920_hsa_dRNA_Huh7_EBOV_6h_1'],
    ['hsa_dRNA_Huh7_EBOV_24h_1', 'SQK-RNA002', 'FLO-PRO002', '20220920_hsa_dRNA_Huh7_EBOV_24h_1'],
    ['hsa_PCRcDNA_Huh7_EBOV_mock_1', 'SQK-PCB111-24', 'FLO-PRO002', '20220922_hsa_PCRcDNA_Huh7_EBOV_0_6_24h_1', '01'],
    ['hsa_PCRcDNA_Huh7_EBOV_6h_1', 'SQK-PCB111-24', 'FLO-PRO002', '20220922_hsa_PCRcDNA_Huh7_EBOV_0_6_24h_1', '02'],
    ['hsa_PCRcDNA_Huh7_EBOV_24h_1', 'SQK-PCB111-24', 'FLO-PRO002', '20220922_hsa_PCRcDNA_Huh7_EBOV_0_6_24h_1', '03'],
]

# FLAIR variables
FLAIR_DIR: "analysis/flair"
FLAIR_METADATA: {
    'all': [
      ['mock1drna', 'mock', 'batch1', 'samples/hsa_dRNA_Huh7_mock_1/fastq/reads.fastq.gz'],
      ['EBOV6h1drna', 'ebov', 'batch1', 'samples/hsa_dRNA_Huh7_EBOV_6h_1/fastq/reads.fastq.gz'],
      ['EBOV24h1drna', 'ebov', 'batch1', 'samples/hsa_dRNA_Huh7_EBOV_24h_1/fastq/reads.fastq.gz'],
      ['EBOVmock1pcr', 'mock', 'batch1', 'samples/hsa_PCRcDNA_Huh7_EBOV_mock_1/fastq/reads.fastq.gz'],
      ['EBOV6h1pcr', 'ebov', 'batch1', 'samples/hsa_PCRcDNA_Huh7_EBOV_6h_1/fastq/reads.fastq.gz'],
      ['EBOV24h1pcr', 'ebov', 'batch1', 'samples/hsa_PCRcDNA_Huh7_EBOV_24h_1/fastq/reads.fastq.gz'],
    ]
}
